version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-1
    restart: always 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Oo_454545
    ports:
      - "1445:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  webapp:
    build: .
    container_name: webapp-1
    # KRİTİK NOKTA: Kapanırsa hemen tekrar aç!
    restart: always 
    depends_on:
      - mssql
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=ITHelpDesk;User Id=sa;Password=Oo_454545;TrustServerCertificate=True;MultipleActiveResultSets=true;

volumes:
  mssql_data: